import type { StylePreset } from './types';

export const PRESETS: StylePreset[] = [
  {
    id: 'capcut-bold',
    name: 'CapCut Bold',
    fontFamily: 'Archivo Black',
    fontSize: 36,
    fontWeight: 900,
    color: '#FFFFFF',
    bgColor: '#E63946',
    bgPadding: 10,
    bgBorderRadius: 6,
    outlineWidth: 0,
    outlineColor: 'transparent',
    shadowBlur: 0,
    shadowColor: 'transparent',
    letterSpacing: 0,
    textTransform: 'uppercase',
    animation: { type: 'pop', wordDelay: 80, duration: 200, easing: 'cubic-bezier(0.34,1.56,0.64,1)' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'karaoke-glow',
    name: 'Karaoke Glow',
    fontFamily: 'Poppins',
    fontSize: 34,
    fontWeight: 700,
    color: '#AAAAAA',
    bgColor: 'rgba(0,0,0,0.4)',
    bgPadding: 8,
    bgBorderRadius: 4,
    outlineWidth: 0,
    outlineColor: 'transparent',
    shadowBlur: 12,
    shadowColor: '#FFD700',
    letterSpacing: 1,
    textTransform: 'none',
    animation: { type: 'karaoke', wordDelay: 0, duration: 150, easing: 'ease-out' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    fontFamily: 'DM Sans',
    fontSize: 30,
    fontWeight: 400,
    color: '#E8F4F8',
    bgColor: 'rgba(0,0,0,0.55)',
    bgPadding: 12,
    bgBorderRadius: 4,
    outlineWidth: 0,
    outlineColor: 'transparent',
    shadowBlur: 0,
    shadowColor: 'transparent',
    letterSpacing: 2,
    textTransform: 'none',
    animation: { type: 'typewriter', wordDelay: 0, duration: 600, easing: 'linear' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'bounce-pop',
    name: 'Bounce Pop',
    fontFamily: 'Space Grotesk',
    fontSize: 36,
    fontWeight: 700,
    color: '#FFFFFF',
    bgColor: '#2D6A4F',
    bgPadding: 10,
    bgBorderRadius: 20,
    outlineWidth: 2,
    outlineColor: '#95D5B2',
    shadowBlur: 0,
    shadowColor: 'transparent',
    letterSpacing: 0,
    textTransform: 'none',
    animation: { type: 'bounce', wordDelay: 100, duration: 300, easing: 'cubic-bezier(0.68,-0.55,0.27,1.55)' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'slide-up',
    name: 'Slide Up',
    fontFamily: 'Manrope',
    fontSize: 32,
    fontWeight: 600,
    color: '#FFFFFF',
    bgColor: 'rgba(0,0,0,0.0)',
    bgPadding: 8,
    bgBorderRadius: 0,
    outlineWidth: 2,
    outlineColor: '#000000',
    shadowBlur: 8,
    shadowColor: 'rgba(0,0,0,0.6)',
    letterSpacing: 0,
    textTransform: 'none',
    animation: { type: 'slide-up', wordDelay: 80, duration: 250, easing: 'cubic-bezier(0.22,1,0.36,1)' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'minimal-shadow',
    name: 'Minimal Shadow',
    fontFamily: 'Inter',
    fontSize: 30,
    fontWeight: 400,
    color: '#FFFFFF',
    bgColor: undefined,
    bgPadding: 0,
    bgBorderRadius: 0,
    outlineWidth: 0,
    outlineColor: 'transparent',
    shadowBlur: 16,
    shadowColor: 'rgba(0,0,0,0.9)',
    letterSpacing: 0.5,
    textTransform: 'none',
    animation: { type: 'fade', wordDelay: 0, duration: 400, easing: 'ease-in-out' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'neon-outline',
    name: 'Neon Outline',
    fontFamily: 'Oswald',
    fontSize: 40,
    fontWeight: 700,
    color: '#FFFFFF',
    bgColor: undefined,
    bgPadding: 0,
    bgBorderRadius: 0,
    outlineWidth: 3,
    outlineColor: '#00F5FF',
    shadowBlur: 20,
    shadowColor: '#00F5FF',
    letterSpacing: 4,
    textTransform: 'uppercase',
    animation: { type: 'neon-pulse', wordDelay: 60, duration: 400, easing: 'ease-out' },
    position: { x: 0.5, y: 0.82 },
  },
  {
    id: 'handwritten',
    name: 'Handwritten',
    fontFamily: 'Caveat',
    fontSize: 38,
    fontWeight: 700,
    color: '#FFF8E7',
    bgColor: undefined,
    bgPadding: 0,
    bgBorderRadius: 0,
    outlineWidth: 0,
    outlineColor: 'transparent',
    shadowBlur: 6,
    shadowColor: 'rgba(0,0,0,0.5)',
    letterSpacing: 1,
    textTransform: 'none',
    animation: { type: 'typewriter', wordDelay: 0, duration: 500, easing: 'linear' },
    position: { x: 0.5, y: 0.82 },
  },
];

export const DEFAULT_PRESET = PRESETS[0];
